version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ./web:/usr/share/nginx/html
    restart: unless-stopped
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8080}
      - API_URL=${API_URL:-http://localhost:8080/api}