name: autoparts
description: "Otomotiv yedek parça stok yönetim sistemi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  printing: ^5.11.1
  pdf: ^3.10.7
  dio: ^5.4.0
  get_it: ^7.6.7
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.1
  intl: ^0.19.0
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  barcode_widget: ^2.0.4
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf 