FROM golang:1.24-alpine

# Install necessary development tools
RUN apk add --no-cache gcc musl-dev git ca-certificates tzdata

# Set working directory
WORKDIR /app

# Copy application files
COPY . .

# Build the application
RUN go build -o main ./cmd/server/main.go

# Expose application port
EXPOSE 8080

# Run the application
CMD ["./main"]